import LuasDoorHero from "@/components/ui/luas-door-hero";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import ScoreTicker from "@/components/whimsy/ScoreTicker";

export default function HomePage() {
  return <>
    {/* The header (with its skip link) must stay inside the hero's children: the hero only intercepts in-page anchors inside its own section. */}
    <LuasDoorHero title="Find a home that fits your life" cta={{ label: "Find my home", href: "/preferences" }} skipTargetId="main-content">
      <SiteHeader variant="overlay" actions={<a className="back" href="#how-it-works">How it works</a>} />
    </LuasDoorHero>
    <main id="main-content" tabIndex={-1} className="shell"><section className="hero hero-grid"><div><div className="eyebrow">Housing search, rethought</div><h2 className="hero-heading">Search by the life you live, not the postcode.</h2><p className="lede">Tell us where you need to go, how you travel and what you can afford. We’ll find homes that work — including places you may not have considered.</p><Link className="button" href="/preferences">Find my home <span aria-hidden="true">→</span></Link></div><div className="hero-card" aria-label="Example HomeMatch results"><div className="eyebrow">A better way to search</div><div className="mini-result"><div className="mini-top"><strong>Best overall fit</strong><p className="score-tile compact"><span className="score-tile-value" data-value={92}><ScoreTicker value={92} /><span className="score-tile-unit">%</span></span><span className="score-tile-label">match</span></p></div><div>Two-bed home · Dublin 8</div><small className="muted">€1,650/month · 22 min to work</small></div><div className="mini-result"><div className="mini-top"><strong>Worth considering</strong><p className="score-tile compact"><span className="score-tile-value" data-value={87}><ScoreTicker value={87} /><span className="score-tile-unit">%</span></span><span className="score-tile-label">match</span></p></div><div>Station-side apartment · Tallaght</div><small className="muted">€350 cheaper · direct Luas connection</small></div><p className="muted">We rank homes by how well they fit your life, not just by postcode.</p></div></section><ol className="steps" id="how-it-works" aria-label="How HomeMatch works"><li className="step"><span className="eyebrow">Stop 01</span><strong>Tell us about your life</strong><span className="muted">Your budget, destinations and preferred ways to travel.</span></li><li className="step"><span className="eyebrow">Stop 02</span><strong>See the trade-offs</strong><span className="muted">Every recommendation explains why it matches.</span></li><li className="step"><span className="eyebrow">Stop 03</span><strong>Discover more options</strong><span className="muted">Find homes beyond the areas you already know.</span></li></ol></main>
  </>;
}
