import Link from "next/link";
import LuasDoorHero from "@/components/ui/luas-door-hero";

export default function HomePage() {
  return <>
    <LuasDoorHero title="Find a home that fits your life" cta={{ label: "Find my home", href: "/preferences" }} skipTargetId="main-content">
      <a className="skip-link" href="#main-content">Skip to content</a>
      <nav className="nav hero-nav" aria-label="Main navigation"><Link className="brand" href="/">Home<span>Match</span></Link><Link href="/preferences">How it works</Link></nav>
    </LuasDoorHero>
    <main id="main-content" tabIndex={-1} className="shell"><section className="hero hero-grid"><div><div className="eyebrow">Housing search, rethought</div><h2 className="hero-heading">Search by the life you live, not the postcode.</h2><p className="lede">Tell us where you need to go, how you travel and what you can afford. We’ll find homes that work — including places you may not have considered.</p><Link className="button" href="/preferences">Find my home <span aria-hidden="true">→</span></Link></div><div className="hero-card" aria-label="Example HomeMatch results"><div className="eyebrow">A better way to search</div><div className="mini-result"><div className="mini-top"><strong>Best overall fit</strong><span className="score">92% match</span></div><div>Two-bed home · Dublin 8</div><small className="muted">€1,650/month · 22 min to work</small></div><div className="mini-result"><div className="mini-top"><strong>Worth considering</strong><span className="score">87% match</span></div><div>Station-side apartment · Tallaght</div><small className="muted">€350 cheaper · direct Luas connection</small></div><p className="muted">We rank homes by how well they fit your life, not just by postcode.</p></div></section><section className="steps" aria-label="How HomeMatch works"><div className="step"><span className="eyebrow">01</span><strong>Tell us about your life</strong><span className="muted">Your budget, destinations and preferred ways to travel.</span></div><div className="step"><span className="eyebrow">02</span><strong>See the trade-offs</strong><span className="muted">Every recommendation explains why it matches.</span></div><div className="step"><span className="eyebrow">03</span><strong>Discover more options</strong><span className="muted">Find homes beyond the areas you already know.</span></div></section></main>
  </>;
}
