import type { Commute, DestinationType, Property, TransportMode } from "./types";

export const properties: Property[] = [
  { id:"dawson-house-d8", title:"Furnished apartment by Christchurch", area:"Dublin 8", address:"Apartment 4, Dawson House, Dean Court, Patrick Street, Christchurch, Dublin 8", listingType:"rent", price:1950, bedrooms:1, bathrooms:1, type:"Apartment", description:"First-floor one-bed with a fitted kitchen and open living/dining space, a short walk from Temple Bar and St Stephen's Green.", parking:false, furnished:true, facilities:["Central Heating", "Washing Machine", "Microwave"], ber:"Exempt", daftUrl:"https://www.daft.ie/for-rent/apartment-4-dawson-house-dean-court-patrick-street-christchurch-dublin-8/6685622", lat:53.339437, lng:-6.27284, nearbyTransport:"City-centre bus routes nearby", transportQuality:"Good", image:"⛪" },
  { id:"pembroke-place-d2", title:"Bright one-bed off Baggot Street", area:"Dublin 2", address:"Apartment 2, 6 Pembroke Place, Dublin 2", listingType:"rent", price:1850, bedrooms:1, bathrooms:1, type:"Apartment", description:"Light-filled one-bedroom apartment in the Georgian core, close to Trinity College and the Grand Canal Dock employers.", parking:false, furnished:true, facilities:["Central Heating", "Microwave", "Internet", "Washing Machine"], ber:"B2", daftUrl:"https://www.daft.ie/for-rent/apartment-2-6-pembroke-place-dublin-2/6587184", lat:53.334167, lng:-6.254178, nearbyTransport:"City-centre bus routes nearby", transportQuality:"Good", image:"🏙️" },
  { id:"smithfield-village-d7", title:"Smithfield Square apartment with balcony", area:"Dublin 7", address:"Smithfield Village Apartments, Smithfield, Dublin 7", listingType:"rent", price:1700, bedrooms:1, bathrooms:1, type:"Apartment", description:"Fully furnished one-bed on Smithfield Square with an open-plan living area and a private balcony.", parking:false, furnished:true, facilities:["Dryer", "Microwave", "Washing Machine", "Garden/Patio/Balcony"], ber:"C3", daftUrl:"https://www.daft.ie/for-rent/smithfield-village-apartments-smithfield-dublin-7/6685738", lat:53.348563, lng:-6.277082, nearbyTransport:"Luas Red Line nearby", transportQuality:"Good", image:"🚋" },
  { id:"mountjoy-square-d1", title:"Top-floor Georgian one-bed", area:"Dublin 1", address:"Mountjoy Square East, F9, Dublin 1", listingType:"rent", price:1750, bedrooms:1, bathrooms:1, type:"Apartment", description:"Newly refurbished top-floor apartment on a Georgian square, with a modern kitchen and permit parking available.", parking:false, furnished:true, facilities:["Central Heating", "Dryer", "Internet", "Washing Machine"], ber:"Exempt", daftUrl:"https://www.daft.ie/for-rent/mountjoy-square-east-f9-dublin-1/6684724", lat:53.357719, lng:-6.256974, nearbyTransport:"Northside bus corridors nearby", transportQuality:"Good", image:"🏛️" },
  { id:"connaught-street-d7", title:"Refurbished Phibsborough one-bed", area:"Dublin 7", address:"Connaught Street, Phibsborough, Dublin 7", listingType:"rent", price:1650, bedrooms:1, bathrooms:1, type:"Apartment", description:"Newly refurbished one-bed with a modern shower room, close to Phibsborough village and the Luas Green Line.", parking:false, furnished:true, facilities:["Dryer", "Internet", "Washing Machine", "Microwave"], ber:"Exempt", daftUrl:"https://www.daft.ie/for-rent/connaught-street-phibsborough-dublin-7/6686276", lat:53.36308, lng:-6.275382, nearbyTransport:"Luas Green Line nearby", transportQuality:"Good", image:"🌳" },
  { id:"riverbank-hall-d11", title:"Two-bed beside the Botanic Gardens", area:"Glasnevin, Dublin 11", address:"Riverbank Hall, Addison Park, Glasnevin, Dublin 11", listingType:"rent", price:2500, bedrooms:2, bathrooms:2, type:"Apartment", description:"Spacious two-double-bed apartment with an ensuite, balcony and private parking, next to the Botanic Gardens.", parking:true, furnished:false, facilities:["Alarm", "Dishwasher", "Central Heating", "Parking", "Washing Machine", "Microwave"], ber:"B3", daftUrl:"https://www.daft.ie/for-rent/riverbank-hall-addison-park-glasnevin-dublin-11/6685667", lat:53.376827, lng:-6.276679, nearbyTransport:"Botanic Road buses nearby", transportQuality:"Good", image:"🌿" },
  { id:"sunnyside-d5", title:"Renovated two-bed on Malahide Road", area:"Killester, Dublin 5", address:"1 Sunnyside, Malahide Road, Killester, Dublin 5", listingType:"rent", price:2500, bedrooms:2, bathrooms:1, type:"Apartment", description:"Newly renovated second-floor two-bed with lift access, underground parking and pets allowed.", parking:true, furnished:true, facilities:["Parking", "Central Heating", "Pets Allowed", "Alarm", "Washing Machine", "Dishwasher", "Microwave"], ber:"B3", daftUrl:"https://www.daft.ie/for-rent/1-sunnyside-malahide-road-dublin-5-killester-co-dublin/6679797", lat:53.381088, lng:-6.207934, nearbyTransport:"Malahide Road buses nearby", transportQuality:"Good", image:"🐾" },
  { id:"dublin-12-family", title:"Family home near the green line", area:"Dublin 12", address:"Dublin 12 (sample listing)", listingType:"buy", price:425000, bedrooms:3, bathrooms:2, type:"House", description:"A practical three-bedroom home with a garden and straightforward city access.", parking:true, furnished:false, facilities:["Parking", "Garden"], lat:53.3255, lng:-6.317, nearbyTransport:"10 min walk to the Luas", transportQuality:"Good", image:"🏘️" },
  { id:"swords-commuter", title:"Modern commuter apartment", area:"Swords", address:"Swords, Co. Dublin (sample listing)", listingType:"buy", price:315000, bedrooms:2, bathrooms:2, type:"Apartment", description:"A modern apartment with generous space and a direct bus connection into Dublin.", parking:true, furnished:false, facilities:["Parking"], lat:53.4597, lng:-6.2181, nearbyTransport:"3 min walk to frequent bus routes", transportQuality:"Good", image:"🏢" },
];

export function getProperty(id: string) { return properties.find((item) => item.id === id); }

const mockCommuteMinutes: Record<string, Record<DestinationType, Partial<Record<TransportMode, number>>>> = {
  "dublin-12-family": { work:{ bike:22, bus:31, train:28 }, "partner-work":{ bike:26, bus:34, train:31 }, family:{ bike:28, bus:36, train:32 }, university:{ bike:24, bus:30 }, school:{ bike:15, bus:20 }, other:{ bike:28, bus:35 } },
  "swords-commuter": { work:{ bus:34, bike:52 }, "partner-work":{ bus:38, bike:56 }, family:{ bus:45, bike:65 }, university:{ bus:40, bike:58 }, school:{ bus:25, bike:35 }, other:{ bus:40, bike:58 } },
};

const modeLabels: Record<TransportMode, string> = { car:"Driving", train:"Train", bus:"Bus", bike:"Cycling", walk:"Walking" };

/** Hand-written fallback, used only when a destination can't be geocoded or no transit data has been generated. */
export function getMockCommute(propertyId: string, destinationType: DestinationType, modes: TransportMode[]): Commute {
  const property = getProperty(propertyId);
  const table = mockCommuteMinutes[propertyId]?.[destinationType];
  // Without a table entry, approximate using the straight-line distance to O'Connell Bridge.
  const km = property ? Math.hypot((property.lat - 53.3473) * 111, (property.lng + 6.2591) * 66) : 5;
  const options: Partial<Record<TransportMode, number>> = table ?? { walk: Math.round(km * 16), bike: Math.round(km * 5 + 3), bus: Math.round(km * 5 + 10), train: Math.round(km * 4 + 10), car: Math.round(km * 4 + 8) };
  const available = modes.map((mode) => ({ mode, minutes: options[mode] })).filter((item): item is { mode: TransportMode; minutes: number } => item.minutes !== undefined);
  const best = available.sort((a, b) => a.minutes - b.minutes)[0] ?? { mode: "bus" as TransportMode, minutes: 60 };
  return { ...best, summary: `${modeLabels[best.mode]} (rough estimate)`, transportQuality: property?.transportQuality ?? "Limited", source: "mock" };
}
